%% FIX problem
% Greedy search
RSL_num = 3; % RSL_num is the number of RSL
[x_opt_greedy,KL_min] = GreedySearch(PG_array,POM_GT,lob,RSL_num);

% % Bayesian optimization 
% X1 = optimizableVariable('X1',[1 num_RSL_cfgs],'Type','integer');
% X2 = optimizableVariable('X2',[1 num_RSL_cfgs],'Type','integer');
% X3 = optimizableVariable('X3',[1 num_RSL_cfgs],'Type','integer');
% fun = @(I) objectiveFunction([I.X1 I.X2 I.X3],POM_GT,PG_array);
% iterations_max = 200;
% results = bayesopt(fun,[X1 X2 X3],...
%     'IsObjectiveDeterministic',true,...
%     'MaxObjectiveEvaluations',iterations_max,'NumSeedPoints',10,...
%     'AcquisitionFunctionName','expected-improvement-plus',...
%     'XConstraintFcn',@xconstraint);

% %GA
% rng default
% lb = zeros(1,num_RSL_cfgs);
% ub = ones(1,num_RSL_cfgs);
% 
% % configure GA
% options = optimoptions('ga', ...
%     'PopulationType', 'bitstring', ...
%     'CreationFcn', @my_creation, ...
%     'CrossoverFcn', @crossoversinglepoint, ...
%     'MutationFcn', {@mutationuniform, 0.02}, ...
%     'PopulationSize', 200, ...
%     'MaxGenerations', 2000, ...
%     'Display', 'iter', ...
%     'UseParallel',true,...
%     'PlotFcn', @gaplotbestf ...
% );
% options.FunctionTolerance = 1e-9;
% % 运行优化
% [rsl_opt, fval] = ga(@(x)EstFitness_FIX(x,POM_GT,PG_array,RSL_num), ...
%     num_RSL_cfgs,[],[],[],lb,ub,[],[],options);
